Feature/#9
PillOnPhone/client pull request #10
Opened 2024-06-01 12:22 UTC by Kyujenius

## 관련 이슈
- Resolves : #9 
 
## 작업 사항
- 채팅 종류 다양화 (init, Recommend)
- 헤더 추가(기존의 DefaultAppBar와 사이즈가 아이콘 맞지 않음 24 != 32, centerTitle = true)
- 아이콘 추가(send.svg, leaving_chatting.svg)

- 작동은 아래와 같이 이루어집니다.
![PillOnPhone 구동과정](https://github.com/PillOnPhone/client/assets/120018983/ff4434f7-8dac-4383-a0b0-bad930029d01)

## 참고 사항
- 없습니다!

2024-06-02 13:14 UTC, HyungJoonSon requested changes
아래 사항들 확인하고 리팩토링 해주세요

2024-06-02 13:16 UTC, HyungJoonSon commented on lib/view/chatting/chatting_list_screen.dart
> +
한 폴더 내에 이렇게 screen을 2개 이상 넣으면 Widget이 섞일 수 있습니다. 각각 분리해주세요

2024-06-02 13:16 UTC, HyungJoonSon commented on lib/entity/Chat/chat_model.dart
>  class ChatModel {
이름 MessageState로 변경해주세요. 이렇게 하면 사람이 바로 어떤 State인지 알 수 있겠죠?

2024-06-02 13:16 UTC, HyungJoonSon commented on lib/view/chatting/chatting_room_screen.dart
>    const ChattingScreen({super.key});
위에서 말한 것과 동일합니다. 그리고 file name과 class name을 동일시 해주세요

2024-06-02 13:18 UTC, HyungJoonSon commented on lib/widget/app_bar/chatting_app_bar.dart
해당 Class는 왜 생성된건가요?

2024-06-02 16:06 UTC, Kyujenius commented on lib/widget/app_bar/chatting_app_bar.dart
최대한 figama 에서 주어진대로 작업하려다가 이렇게 되었습니다..!
- figma에서는 약국의 이름을 앱바 중앙에 띄워줍니다.
- 그러나 DefaultBackAppBar의 centerTitle 값이 false로 고정이라 이 값을 선택적으로 할 수 있게끔 만들고싶었는데, 이미 DefaultBackAppBar 가 사용되고 있는 곳에서 어떤 문제가 발생할지 모르겠어서 우선은 이렇게 만들게 되었습니다. 추후에 수정하라면 하겠습니다! 
- 지속적으로 사용되는 custom_icon_button 의 크기가 width: 32, height :32 인 반면에, DefaultBackAppBar 에서 사용하는 뒤로가기 svg 가 width: 24 height: 24 인 이유로 small_custom_icon_button(width: 24 height: 24)도 만들게 되었습니다.

2024-06-02 16:07 UTC, Kyujenius commented
넵 모든 comment 전부 참고하겠습니다!!

2024-06-03 11:19 UTC, HyungJoonSon commented on lib/widget/app_bar/chatting_app_bar.dart
그러면 DefaultBackAppBar로 해서 왼쪽으로 만들어주시고, 일단 32로 해주세유

2024-06-04 07:02 UTC, Kyujenius commented on lib/widget/app_bar/chatting_app_bar.dart
넵 완료했습니다!

2024-06-04 09:35 UTC, HyungJoonSon approved these changes
고생하셨습니다

2024-06-04 09:35 UTC, merged