Feature/#3
PillOnPhone/client pull request #4
Opened 2024-05-23 05:42 UTC by Kyujenius

## 관련 이슈
- Resolves : #3  
 
## 작업 사항
- chatting_screen 초기 세팅
- binding 설정

## 참고 사항
- intl 0.18.1을 사용하려면 flutter SDK를 낮춰야 하는데, SDK를 낮추면 아래의 SDK의 버전에 부합하지 않는 문제가 있습니다. 
- UI 확인 시에는 0.19.0으로 실행후 commit 시에는 0.18.1로 버전 낮춰서 작업 진행중에 있습니다. 

<img width="295" alt="image" src="https://github.com/PillOnPhone/client/assets/120018983/5b355f85-a3c1-4e49-911f-0f2001bb38e2">

![image](https://github.com/PillOnPhone/client/assets/120018983/de1b871d-3da5-4178-a6ec-d643949b3ac8)

구현 결과는 아래와 같습니다.
<img width="495" alt="image" src="https://github.com/PillOnPhone/client/assets/120018983/328398e9-7092-4cfb-bf33-4955abd436a3">

2024-05-23 07:01 UTC, HyungJoonSon requested changes
아래 사항들 고쳐주세요

2024-05-23 07:01 UTC, HyungJoonSon commented on lib/view/chatting/chatting_screen.dart
> +    );
필요 없습니다. 그냥 BaseScreen 보면 viewModel로 바로 접근 할 수 있어요.

GetView는 기본적으로 Templete에 들어온 ViewModel을 의존성 주입을 해줍니다.

2024-05-23 07:02 UTC, HyungJoonSon commented on lib/view/chatting/chatting_screen.dart
>      );
기본적으로 정렬 해주세요. 코드를 작성하고 정렬하는 것은 기본 중에 기본입니다.

2024-05-23 07:03 UTC, HyungJoonSon commented on lib/view/chatting/widget/chatting_list_widget.dart
> +            ),
이런 부분에 있어서 저였다면 다음과 같이 Method로 선언만 할 거 같습니다.

[해당 부분]
pharmacyImage(),

[밑에 Method 선언]
Widget pharmacyImage() => ClipRRect(
              borderRadius: BorderRadius.circular(8.0),
              child: Container(
                width: 88,
                height: 88,
                decoration: BoxDecoration(
                  image: DecorationImage(
                    image: NetworkImage(chatItem.pharmacyImage ?? ''),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
            );

2024-05-23 07:04 UTC, HyungJoonSon commented on lib/view/chatting/widget/chatting_list_widget.dart
> +            ),
아래도 동일 합니다. 가독성이 훨씬 좋아지겠죠?

2024-05-23 07:04 UTC, HyungJoonSon commented on lib/view_model/chatting/chatting_view_model.dart
> +  ChattingViewModel();
선언 필요 없습니다

2024-05-23 07:08 UTC, HyungJoonSon commented on lib/view_model/chatting/chatting_view_model.dart
> +  var errorMessage = ''.obs;
이렇게 선언하면 Getx의 생명주기를 모르고 사용하는 것과 같습니다.
OnInit, OnReady 와 같이 생명주기를 알고 사용해보세요. App의 상명주기는 Web과 다르게 OS 위에서 실행되기 때문에 매우 중요합니다.

```Dart
late final RxList<CharListItemModel> chatItems;
late final RxBool isLoading;
late final RxString errorMessage;

@Override
onInit() {
  // 기본 코드가 들어가는 곳
  chatItems = <ChatListItemModel>[].obs;
  isLoading = false.obs;
  errorMessage = ''.obs;
}
```

2024-05-23 07:08 UTC, HyungJoonSon commented on lib/view_model/chatting/chatting_view_model.dart
> +  ];
정렬!

2024-05-23 07:08 UTC, HyungJoonSon commented on pubspec.yaml
> +  dio: ^5.4.3+1
dio 삭제!

2024-05-23 07:08 UTC, Kyujenius commented on lib/view/chatting/chatting_screen.dart
> +    );
네 확인했습니다!

2024-05-23 07:09 UTC, HyungJoonSon commented on lib/entity/Chat/chat_model.dart
> +  });
1. copyWith Method 추가

2. factory를 사용한 fromJson(Map<String, dynamic> data) Method 추가

2024-05-23 09:56 UTC, Kyujenius commented
Comment 전부 반영했습니다!

2024-05-23 14:22 UTC, hyungjoon-son commented on lib/view_model/chatting/chatting_view_model.dart
> +import '../../entity/Chat/chat_model.dart';
절대경로로!

2024-05-23 14:22 UTC, HyungJoonSon requested changes
import할 때 절대경로로만 바꿔줘요

2024-05-23 14:23 UTC, Kyujenius commented on lib/view_model/chatting/chatting_view_model.dart
> +import '../../entity/Chat/chat_model.dart';
넵 알겠습니다!

2024-05-28 04:31 UTC, HyungJoonSon commented on lib/view/chatting/chatting_room_screen.dart
> +          ),
이렇게 column 안에 선언하지 말고 buildAppBar() Method를 Override 해서 선언 해야 합니다.

또한, DefaultAppBar를 사용하고, IconButton은 CustomIconButton을 사용해주세요

2024-05-28 04:33 UTC, HyungJoonSon commented on lib/view/chatting/widget/chatting_list_widget.dart
> +        Get.to(() => const ChattingScreen());
Get.toNamed로 해야해요

2024-05-28 04:33 UTC, HyungJoonSon commented on lib/view/chatting/widget/chatting_list_widget.dart
> +  const ChatListItem({super.key, required this.chatListItem});
위도 순서가 다른데

Flutter는 생성자 -> 필드변수 순서입니다.

2024-05-28 04:34 UTC, HyungJoonSon requested changes
Review 확인해주세요!

2024-05-28 11:37 UTC, Kyujenius commented on lib/view/chatting/chatting_room_screen.dart
> +          ),
넵

2024-05-28 11:37 UTC, Kyujenius commented on lib/view/chatting/widget/chatting_list_widget.dart
> +        Get.to(() => const ChattingScreen());
넵!

2024-05-28 11:37 UTC, Kyujenius commented on lib/view/chatting/widget/chatting_list_widget.dart
> +  const ChatListItem({super.key, required this.chatListItem});
넵

2024-05-31 10:37 UTC, merged